#FIND_PACKAGE(c_urg REQUIRED)
FIND_PATH(URG_INCLUDE_DIR NAMES urg/UrgDevice.h)
MESSAGE(STATUS "FOUND URG headers =" ${URG_INCLUDE_DIR})
INCLUDE_DIRECTORIES(${URG_INCLUDE_DIR})

#Fix Me: Find library doesn't work for me with few names
#FIND_LIBRARY(URG_LIBRARIES NAMES c_urg c_urg_system c_urg_connection PATH /usr/local/lib)
FIND_LIBRARY(URG_LIBRARY NAMES c_urg PATH /usr/local/lib)
FIND_LIBRARY(URG_SYSTEM_LIBRARY NAMES c_urg_system PATH /usr/local/lib)
FIND_LIBRARY(URG_CONNECTION_LIBRARY NAMES c_urg_connection PATH /usr/local/lib)
SET(URG_LIBRARIES ${URG_SYSTEM_LIBRARY} ${URG_LIBRARY} ${URG_CONNECTION_LIBRARY})
MESSAGE(STATUS "Found URG_LIBRARIES ="${URG_LIBRARIES})

SET(URG_FOUND TRUE)

IF(NOT URG_LIBRARIES)
SET(URG_FOUND FALSE)
ENDIF(NOT URG_LIBRARIES)
